### ISSUE TITLE
Inline course addition

### ISSUE THREAD

**Issue by justinkrol** [justinkrol/Gradepal#1]
#### Story

Rather than navigating to a new page, the user adds a new course directly on the courses page without any page loads.
#### Flow
- On courses index page
- Click 'add course'
- Enter information in fields
- Click submit (checkmark)
- Course appears as part of the list
#### Tasks
- [ ] Update tests
- [x] Remove code for 'new course' page
- [x] Show form on click of 'Add course'

On click of 'Submit'
- [x] Create new course in db
- [x] Update view

**Comment by jktin12** [comment]
Use ng-include
