### ISSUE TITLE
Inline course editing

### ISSUE THREAD

**Issue by justinkrol** [justinkrol/Gradepal#3]
#### Story

Rather than navigating to a new page, the user edits a course directly on the courses page without any page loads.
#### Flow
- On courses index page
- Click 'edit' on a specific course
- Change information in fields
- Click submit (checkmark)
- Changes appear immediately in view
#### Tasks
- [ ] Update tests
- [x] Remove code for 'edit course' page (form.html template)
- [x] Refactor to use an angular directive
- [x] Show editable fields on click of 'edit'

On click of 'Submit'
- [x] Put changes to db
- [x] Update view
